[package]
name = "rustyaskar"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rustyaskar"
test = false
bench = false

[dependencies]
tokio = { version = "1.25.0", features = ["full"] }
aries-askar = "0.2.7"
