[package]
name = "rustyoidc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
url = "2.2.2"
env_logger = "0.9.0"
openidconnect = "2.1.2"
